/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVarianceRouteImport } from './routes/_authenticated/variance'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrepRouteImport } from './routes/_authenticated/prep'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInterCompanyRouteImport } from './routes/_authenticated/inter-company'
import { Route as AuthenticatedCostsRouteImport } from './routes/_authenticated/costs'
import { Route as AuthenticatedCalculatorsRouteImport } from './routes/_authenticated/calculators'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiManagerRouteImport } from './routes/_authenticated/ai-manager'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVarianceRoute = AuthenticatedVarianceRouteImport.update({
  id: '/variance',
  path: '/variance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrepRoute = AuthenticatedPrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterCompanyRoute =
  AuthenticatedInterCompanyRouteImport.update({
    id: '/inter-company',
    path: '/inter-company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCostsRoute = AuthenticatedCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculatorsRoute =
  AuthenticatedCalculatorsRouteImport.update({
    id: '/calculators',
    path: '/calculators',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiManagerRoute = AuthenticatedAiManagerRouteImport.update({
  id: '/ai-manager',
  path: '/ai-manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai-manager': typeof AuthenticatedAiManagerRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calculators': typeof AuthenticatedCalculatorsRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/inter-company': typeof AuthenticatedInterCompanyRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/prep': typeof AuthenticatedPrepRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/stock': typeof AuthenticatedStockRoute
  '/users': typeof AuthenticatedUsersRoute
  '/variance': typeof AuthenticatedVarianceRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai-manager': typeof AuthenticatedAiManagerRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calculators': typeof AuthenticatedCalculatorsRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/inter-company': typeof AuthenticatedInterCompanyRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/prep': typeof AuthenticatedPrepRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/stock': typeof AuthenticatedStockRoute
  '/users': typeof AuthenticatedUsersRoute
  '/variance': typeof AuthenticatedVarianceRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/ai-manager': typeof AuthenticatedAiManagerRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calculators': typeof AuthenticatedCalculatorsRoute
  '/_authenticated/costs': typeof AuthenticatedCostsRoute
  '/_authenticated/inter-company': typeof AuthenticatedInterCompanyRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/prep': typeof AuthenticatedPrepRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/variance': typeof AuthenticatedVarianceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/sitemap.xml'
    | '/ai-manager'
    | '/analytics'
    | '/calculators'
    | '/costs'
    | '/inter-company'
    | '/inventory'
    | '/invoices'
    | '/prep'
    | '/profile'
    | '/sales'
    | '/staff'
    | '/stock'
    | '/users'
    | '/variance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/sitemap.xml'
    | '/ai-manager'
    | '/analytics'
    | '/calculators'
    | '/costs'
    | '/inter-company'
    | '/inventory'
    | '/invoices'
    | '/prep'
    | '/profile'
    | '/sales'
    | '/staff'
    | '/stock'
    | '/users'
    | '/variance'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/ai-manager'
    | '/_authenticated/analytics'
    | '/_authenticated/calculators'
    | '/_authenticated/costs'
    | '/_authenticated/inter-company'
    | '/_authenticated/inventory'
    | '/_authenticated/invoices'
    | '/_authenticated/prep'
    | '/_authenticated/profile'
    | '/_authenticated/sales'
    | '/_authenticated/staff'
    | '/_authenticated/stock'
    | '/_authenticated/users'
    | '/_authenticated/variance'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/variance': {
      id: '/_authenticated/variance'
      path: '/variance'
      fullPath: '/variance'
      preLoaderRoute: typeof AuthenticatedVarianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prep': {
      id: '/_authenticated/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof AuthenticatedPrepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inter-company': {
      id: '/_authenticated/inter-company'
      path: '/inter-company'
      fullPath: '/inter-company'
      preLoaderRoute: typeof AuthenticatedInterCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costs': {
      id: '/_authenticated/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthenticatedCostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculators': {
      id: '/_authenticated/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof AuthenticatedCalculatorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-manager': {
      id: '/_authenticated/ai-manager'
      path: '/ai-manager'
      fullPath: '/ai-manager'
      preLoaderRoute: typeof AuthenticatedAiManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiManagerRoute: typeof AuthenticatedAiManagerRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCalculatorsRoute: typeof AuthenticatedCalculatorsRoute
  AuthenticatedCostsRoute: typeof AuthenticatedCostsRoute
  AuthenticatedInterCompanyRoute: typeof AuthenticatedInterCompanyRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedPrepRoute: typeof AuthenticatedPrepRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVarianceRoute: typeof AuthenticatedVarianceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiManagerRoute: AuthenticatedAiManagerRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalculatorsRoute: AuthenticatedCalculatorsRoute,
  AuthenticatedCostsRoute: AuthenticatedCostsRoute,
  AuthenticatedInterCompanyRoute: AuthenticatedInterCompanyRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedPrepRoute: AuthenticatedPrepRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVarianceRoute: AuthenticatedVarianceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
